import { Goal } from '../utils/calculations';

type Meal = { name: string; desc: string; kcal: number; protein: number };
type DayPlan = { day: string; meals: Meal[]; totalKcal: number; tip: string };

const DIETS: Record<Goal, DayPlan[]> = {
  perder_peso: [
    { day: 'Lunes', meals: [{ name: 'Avena + frutos rojos', desc: '40g avena, 100g fresas, 200ml leche desc.', kcal: 350, protein: 18 }, { name: 'Ensalada de pollo 150g', desc: 'Lechuga, tomate, pollo a la plancha, 1 cdta aceite', kcal: 400, protein: 38 }, { name: 'Merluza + verduras', desc: '150g merluza, brócoli al vapor', kcal: 350, protein: 32 }], totalKcal: 1650, tip: 'Hidrátate 2.5L y camina 8k pasos' },
    { day: 'Martes', meals: [{ name: 'Yogur + chía', desc: '200g yogur natural + 15g chía', kcal: 300, protein: 15 }, { name: 'Lentejas 100g + ensalada', desc: 'Lentejas, zanahoria, cebolla', kcal: 450, protein: 28 }, { name: 'Tortilla 2 huevos + ensalada', desc: '2 huevos, clara extra, ensalada', kcal: 380, protein: 26 }], totalKcal: 1680, tip: 'Evita azúcar y alcohol hoy' },
    { day: 'Miércoles', meals: [{ name: 'Tostada integral + pavo', desc: 'Pan integral, 60g pavo, aguacate 30g', kcal: 340, protein: 20 }, { name: 'Arroz integral 80g + atún', desc: 'Atún al natural 100g, ensalada', kcal: 420, protein: 34 }, { name: 'Crema de verduras + pollo', desc: '200ml crema, 100g pollo', kcal: 360, protein: 30 }], totalKcal: 1620, tip: 'Añade 20min cardio suave' },
    { day: 'Jueves', meals: [{ name: 'Smoothie verde', desc: 'Espinaca, plátano medio, leche', kcal: 320, protein: 14 }, { name: 'Quinoa 80g + pollo', desc: 'Quinoa, 120g pollo, verduras', kcal: 480, protein: 36 }, { name: 'Salmón 120g + ensalada', desc: 'Salmón plancha, ensalada mixta', kcal: 420, protein: 30 }], totalKcal: 1720, tip: 'Duerme 7-8h' },
    { day: 'Viernes', meals: [{ name: 'Avena + plátano', desc: '40g avena, medio plátano', kcal: 360, protein: 12 }, { name: 'Garbanzos 100g + verduras', desc: 'Garbanzos, pimiento, cebolla', kcal: 430, protein: 22 }, { name: 'Pavo 150g + puré coliflor', desc: 'Pavo plancha, coliflor', kcal: 350, protein: 38 }], totalKcal: 1640, tip: 'Día de fuerza: prioriza proteína' },
    { day: 'Sábado', meals: [{ name: 'Tostadas + huevo', desc: '2 tostadas, 1 huevo, tomate', kcal: 330, protein: 16 }, { name: 'Paella de verduras 100g arroz', desc: 'Arroz, verduras variadas', kcal: 460, protein: 14 }, { name: 'Yogur + nueces 15g', desc: '200g yogur, 15g nueces', kcal: 280, protein: 12 }], totalKcal: 1620, tip: 'Flexibilidad: disfruta sin excesos' },
    { day: 'Domingo', meals: [{ name: 'Tortitas avena', desc: '2 tortitas, miel 5g', kcal: 340, protein: 14 }, { name: 'Pollo 150g + arroz 60g', desc: 'Pollo, arroz integral', kcal: 450, protein: 38 }, { name: 'Sopa + ensalada', desc: 'Sopa verduras, ensalada', kcal: 300, protein: 14 }], totalKcal: 1590, tip: 'Prep meal de la semana hoy' },
  ],
  ganar_musculo: [
    { day: 'Lunes', meals: [{ name: 'Avena 80g + leche + plátano', desc: '80g avena, 250ml leche, plátano', kcal: 550, protein: 24 }, { name: 'Arroz 120g + pollo 180g', desc: 'Arroz blanco, pollo, 1 cdta aceite', kcal: 650, protein: 52 }, { name: 'Requesón 200g + avena', desc: 'Requesón + 30g avena', kcal: 380, protein: 32 }], totalKcal: 2680, tip: 'Superávit limpio: +300 kcal' },
    { day: 'Martes', meals: [{ name: '4 claras + 1 yema + pan', desc: 'Tortilla + 60g pan integral', kcal: 480, protein: 32 }, { name: 'Pasta 120g + carne 150g', desc: 'Pasta integral, ternera magra', kcal: 700, protein: 48 }, { name: 'Batido whey + avena', desc: 'Whey 30g + 50g avena', kcal: 400, protein: 35 }], totalKcal: 2780, tip: 'Entrena pierna hoy' },
    { day: 'Miércoles', meals: [{ name: 'Yogur + granola 60g', desc: 'Yogur griego 200g', kcal: 450, protein: 22 }, { name: 'Arroz 120g + salmón 150g', desc: 'Salmón + arroz + verduras', kcal: 680, protein: 42 }, { name: 'Pavo 180g + patata 200g', desc: 'Patata asada', kcal: 520, protein: 44 }], totalKcal: 2750, tip: 'Descanso activo' },
    { day: 'Jueves', meals: [{ name: 'Avena 80g + whey', desc: 'Avena + whey 25g', kcal: 520, protein: 36 }, { name: 'Lentejas 120g + arroz 60g', desc: 'Mix completo proteína', kcal: 650, protein: 34 }, { name: 'Pollo 180g + arroz 100g', desc: 'Cena alta en proteína', kcal: 600, protein: 52 }], totalKcal: 2770, tip: 'Volumen espalda-pecho' },
    { day: 'Viernes', meals: [{ name: 'Tostada + aguacate + huevos', desc: 'Pan 80g, 3 huevos, aguacate 40g', kcal: 580, protein: 28 }, { name: 'Pasta 120g + atún 120g', desc: 'Pasta + atún + tomate', kcal: 660, protein: 46 }, { name: 'Requesón + frutos secos', desc: '200g requesón + 20g almendras', kcal: 420, protein: 30 }], totalKcal: 2760, tip: 'Enfócate en progresión de cargas' },
    { day: 'Sábado', meals: [{ name: 'Panqueques avena 80g', desc: '3 panqueques, miel 10g', kcal: 540, protein: 24 }, { name: 'Arroz 120g + pollo 180g + ensalada', desc: 'Clásico hipercalórico limpio', kcal: 650, protein: 52 }, { name: 'Batido + plátano', desc: 'Whey + plátano + leche', kcal: 420, protein: 32 }], totalKcal: 2710, tip: 'Cheat meal controlado opcional' },
    { day: 'Domingo', meals: [{ name: 'Huevos + avena 60g', desc: '3 huevos + avena', kcal: 520, protein: 30 }, { name: 'Quinoa 100g + ternera 150g', desc: 'Quinoa + ternera', kcal: 680, protein: 44 }, { name: 'Yogur + avena 40g', desc: 'Yogur griego + avena', kcal: 380, protein: 20 }], totalKcal: 2680, tip: 'Planifica progresión semanal' },
  ],
  definir: [
    { day: 'Lunes', meals: [{ name: 'Claras 4 + avena 40g', desc: 'Claras + avena', kcal: 320, protein: 28 }, { name: 'Pollo 150g + arroz 60g', desc: 'Arroz integral', kcal: 420, protein: 38 }, { name: 'Pescado 150g + verduras', desc: 'Pescado blanco', kcal: 340, protein: 34 }], totalKcal: 1880, tip: 'Déficit suave -250 kcal' },
    { day: 'Martes', meals: [{ name: 'Yogur proteico', desc: 'Yogur + 15g whey', kcal: 280, protein: 30 }, { name: 'Atún 120g + ensalada grande', desc: 'Ensalada completa', kcal: 380, protein: 32 }, { name: 'Pavo 150g + verduras', desc: 'Pavo plancha', kcal: 340, protein: 36 }], totalKcal: 1820, tip: 'Cardio 15min post pesas' },
    { day: 'Miércoles', meals: [{ name: 'Avena 40g + leche', desc: 'Avena + leche desnatada', kcal: 300, protein: 16 }, { name: 'Lentejas 80g + pollo 100g', desc: 'Mix proteína', kcal: 440, protein: 36 }, { name: 'Tortilla 3 claras + ensalada', desc: 'Tortilla clara', kcal: 280, protein: 24 }], totalKcal: 1820, tip: 'Mantén fuerza, sube repeticiones' },
    { day: 'Jueves', meals: [{ name: 'Tostada + pavo 60g', desc: 'Integral + pavo', kcal: 300, protein: 20 }, { name: 'Arroz 60g + salmón 120g', desc: 'Salmón + arroz', kcal: 480, protein: 32 }, { name: 'Requesón 150g', desc: 'Requesón desnatado', kcal: 200, protein: 22 }], totalKcal: 1880, tip: 'Hidratación clave' },
    { day: 'Viernes', meals: [{ name: 'Smoothie proteico', desc: 'Leche + whey 25g + avena 20g', kcal: 320, protein: 28 }, { name: 'Pollo 150g + quinoa 60g', desc: 'Quinoa + pollo', kcal: 460, protein: 38 }, { name: 'Ensalada + atún', desc: 'Atún + verduras', kcal: 340, protein: 30 }], totalKcal: 1920, tip: 'Define abdomen: déficit + core' },
    { day: 'Sábado', meals: [{ name: 'Huevos 2 + pan integral', desc: '2 huevos + 40g pan', kcal: 340, protein: 18 }, { name: 'Arroz 60g + pollo 130g', desc: 'Arroz + pollo', kcal: 420, protein: 36 }, { name: 'Yogur + nueces 10g', desc: 'Yogur + nueces', kcal: 260, protein: 14 }], totalKcal: 1820, tip: 'Disfruta sin romper déficit' },
    { day: 'Domingo', meals: [{ name: 'Avena 40g + yogur', desc: 'Avena + yogur', kcal: 300, protein: 16 }, { name: 'Pasta 60g + ternera 100g', desc: 'Pasta integral', kcal: 440, protein: 28 }, { name: 'Sopa + pollo 100g', desc: 'Sopa + pollo', kcal: 300, protein: 26 }], totalKcal: 1840, tip: 'Meal prep domingo' },
  ],
  resistencia: [
    { day: 'Lunes', meals: [{ name: 'Avena 60g + plátano', desc: 'Energía sostenida', kcal: 420, protein: 14 }, { name: 'Arroz 100g + pollo 130g + verduras', desc: 'Carbos complejos', kcal: 520, protein: 36 }, { name: 'Pasta 80g + atún', desc: 'Recuperación', kcal: 480, protein: 32 }], totalKcal: 2220, tip: 'Carbohidratos = combustible' },
    { day: 'Martes', meals: [{ name: 'Tostadas + miel + yogur', desc: 'Tostadas 60g pan + miel', kcal: 400, protein: 16 }, { name: 'Quinoa 100g + salmón 120g', desc: 'Omega 3', kcal: 580, protein: 34 }, { name: 'Arroz 80g + pavo 130g', desc: 'Cena ligera', kcal: 440, protein: 32 }], totalKcal: 2220, tip: 'Entrena intervalos' },
    { day: 'Miércoles', meals: [{ name: 'Granola 50g + leche', desc: 'Granola + leche', kcal: 380, protein: 12 }, { name: 'Lentejas 100g + arroz 50g', desc: 'Hierro + carb', kcal: 520, protein: 28 }, { name: 'Tortilla + patata 150g', desc: 'Tortilla patata', kcal: 460, protein: 18 }], totalKcal: 2160, tip: 'Hidratación con electrolitos' },
    { day: 'Jueves', meals: [{ name: 'Avena 60g + frutos rojos', desc: 'Antioxidantes', kcal: 380, protein: 14 }, { name: 'Pasta 100g + pollo 130g', desc: 'Carga carb', kcal: 560, protein: 38 }, { name: 'Pescado 130g + arroz 60g', desc: 'Ligero', kcal: 420, protein: 30 }], totalKcal: 2160, tip: 'Rodaje largo hoy' },
    { day: 'Viernes', meals: [{ name: 'Pan 80g + pavo + queso fresco', desc: 'Pan + pavo', kcal: 420, protein: 28 }, { name: 'Arroz 100g + ternera 120g', desc: 'Hierro', kcal: 560, protein: 36 }, { name: 'Yogur + avena 30g + miel', desc: 'Recuperación', kcal: 340, protein: 14 }], totalKcal: 2120, tip: 'Estira 15 min' },
    { day: 'Sábado', meals: [{ name: 'Huevos 2 + avena 40g', desc: 'Mixto', kcal: 400, protein: 20 }, { name: 'Arroz 100g + pollo 130g', desc: 'Pre-competición', kcal: 520, protein: 36 }, { name: 'Sopa + pan + pavo', desc: 'Ligero', kcal: 380, protein: 22 }], totalKcal: 2100, tip: 'Día largo: lleva geles' },
    { day: 'Domingo', meals: [{ name: 'Tortitas avena 60g', desc: 'Tortitas', kcal: 400, protein: 16 }, { name: 'Pasta 80g + verduras + atún', desc: 'Pasta', kcal: 480, protein: 28 }, { name: 'Leche + plátano', desc: 'Recuperación', kcal: 280, protein: 10 }], totalKcal: 1960, tip: 'Descanso total' },
  ],
  mantener: [
    { day: 'Lunes', meals: [{ name: 'Avena 50g + leche', desc: 'Equilibrado', kcal: 360, protein: 16 }, { name: 'Arroz 90g + pollo 140g', desc: 'Comida base', kcal: 520, protein: 38 }, { name: 'Ensalada + pescado 130g', desc: 'Cena ligera', kcal: 380, protein: 30 }], totalKcal: 2060, tip: 'Mantén hábitos' },
    { day: 'Martes', meals: [{ name: 'Yogur + granola 40g', desc: 'Yogur', kcal: 340, protein: 14 }, { name: 'Pasta 90g + ternera 120g', desc: 'Pasta', kcal: 560, protein: 36 }, { name: 'Tortilla 2 huevos + ensalada', desc: 'Tortilla', kcal: 360, protein: 20 }], totalKcal: 2060, tip: 'Equilibrio' },
    { day: 'Miércoles', meals: [{ name: 'Tostada + aguacate 30g + pavo', desc: 'Tostada', kcal: 360, protein: 18 }, { name: 'Lentejas 90g + verduras', desc: 'Lentejas', kcal: 440, protein: 24 }, { name: 'Pollo 140g + arroz 70g', desc: 'Cena', kcal: 480, protein: 36 }], totalKcal: 2080, tip: 'Sigue activo' },
    { day: 'Jueves', meals: [{ name: 'Smoothie avena 40g', desc: 'Smoothie', kcal: 340, protein: 14 }, { name: 'Quinoa 80g + salmón 120g', desc: 'Quinoa', kcal: 540, protein: 32 }, { name: 'Requesón 150g + nueces 10g', desc: 'Requesón', kcal: 280, protein: 20 }], totalKcal: 1960, tip: 'Variedad' },
    { day: 'Viernes', meals: [{ name: 'Huevos 2 + pan 40g', desc: 'Huevos', kcal: 360, protein: 18 }, { name: 'Arroz 90g + atún 100g', desc: 'Arroz', kcal: 480, protein: 32 }, { name: 'Crema verduras + pollo 100g', desc: 'Crema', kcal: 320, protein: 26 }], totalKcal: 1960, tip: 'Mantén' },
    { day: 'Sábado', meals: [{ name: 'Avena 50g + yogur', desc: 'Avena', kcal: 340, protein: 16 }, { name: 'Arroz 80g + pollo 130g', desc: 'Arroz', kcal: 480, protein: 34 }, { name: 'Pescado 130g + patata 150g', desc: 'Pescado', kcal: 400, protein: 28 }], totalKcal: 2020, tip: 'Disfruta' },
    { day: 'Domingo', meals: [{ name: 'Tortitas 50g', desc: 'Tortitas', kcal: 360, protein: 14 }, { name: 'Pasta 80g + pollo 120g', desc: 'Pasta', kcal: 500, protein: 32 }, { name: 'Yogur + fruta', desc: 'Yogur', kcal: 240, protein: 10 }], totalKcal: 1900, tip: 'Planifica semana' },
  ],
};

export function getDietForGoal(goal: Goal) {
  return DIETS[goal] ?? DIETS.mantener;
}
